### ISSUE TITLE
Listing

### ISSUE THREAD

**Issue by Clauber** [Cklauber/StudentHousing#4]
As a LDSBC Student
I want to see the information of the listing of a property
Because I want to have more information about the listing.

Listing Criteria
 - [x] Name (of the place)
 - [x] Contact Name
 - [x] Contact Email
 - [x] Contact Phone#
 - [x] Price per month + Down payment
 - [x] Contact information for whoever is listing
 - [ ] Photos
 - [x] Address
 - [x] Utilities Included with rent
 - [x] Utilities not included with rent
 - [x]  Ammendities
 - [ ] Ratings
 - [x] How many people are signed up
 - [x] Room availability
 - [x] Floorplan (how many bathrooms, bedrooms, kitchen)
 - [ ] Man/Woman only?
 - [ ] How many parking lot available
 - [ ] How long is the contract for
 - [ ] Pet Friendly
 - [ ] Washer, Dryer, and Dishwasher included?

**Comment by Cklauber** [comment]
- [ ] IDE - Luis and Seung
- [ ]
